-- =============================================================================
-- TariffHub master data (schema "master")
--
-- Purpose: let one search compare carriers that price the same shipment in
-- different terms (city, postcode, province, carrier zone, service area,
-- named warehouse). The user enters an address; these tables turn it into
-- the term each carrier prices by.
--
--   address (country, postcode, city, state)
--      -> master.country / country_alias          full names, spelling variants
--      -> master.subdivision                      state / province / prefecture
--      -> master.postcode_area                    postcode -> state, city
--      -> master.service_area_postcode            postcode -> carrier station
--      -> master.zone_scheme + zone_member        -> carrier zone
--      -> master.zone_matrix                      origin zone x dest zone -> rate group
--      -> tariff.*_tariff FREIGHT rows            the price
--
-- Run order: 001_master_schema.sql, then 002_master_seed.sql (generated by
-- tools/build_master.py). Re-runnable: every object is CREATE ... IF NOT EXISTS.
-- See docs/TARIFF_DATA_REVIEW.md for why each table exists.
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS master;
COMMENT ON SCHEMA master IS 'Reference data used to resolve a user address into each carrier''s pricing terms, and labels for filter values.';

-- -----------------------------------------------------------------------------
-- 1. Countries
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS master.country (
    country_code        char(2)      PRIMARY KEY,                 -- ISO 3166-1 alpha-2 (XK for Kosovo)
    iso3_code           char(3),
    iso_numeric         char(3),
    name                varchar(100) NOT NULL,                    -- display name: 'South Korea', 'Czechia', 'Taiwan'
    official_name       varchar(150),                             -- 'Republic of Korea'
    currency_code       char(3),                                  -- main currency, when known
    postcode_regex      varchar(200),                             -- validation; NULL = not maintained yet
    has_postcodes       boolean,                                  -- NULL = unknown
    is_iso              boolean      NOT NULL DEFAULT true,
    active              boolean      NOT NULL DEFAULT true
);
COMMENT ON TABLE master.country IS 'One row per country. The filter shows name and keeps country_code as the value.';

-- Every spelling found in tariff files and the tariff tables, so loaders can map a printed name to a code.
CREATE TABLE IF NOT EXISTS master.country_alias (
    alias_norm          varchar(150) PRIMARY KEY,                 -- upper(trim(alias)), single spaces
    alias               varchar(150) NOT NULL,
    country_code        char(2)      NOT NULL REFERENCES master.country,
    source              varchar(40)  NOT NULL                     -- ISO, RATE_CARD, TARIFF_TABLE, MANUAL
);

-- Codes that carriers print but ISO does not have (or that mean only part of an ISO country).
CREATE TABLE IF NOT EXISTS master.carrier_country_code (
    carrier_code        varchar(10)  NOT NULL,
    printed_code        varchar(5)   NOT NULL,                    -- as on the rate card: XC, KV, IC ...
    name                varchar(100) NOT NULL,
    country_code        char(2)      REFERENCES master.country,   -- ISO country it belongs to
    note                text,
    PRIMARY KEY (carrier_code, printed_code)
);

-- -----------------------------------------------------------------------------
-- 2. Places inside a country
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS master.subdivision (
    subdivision_code    varchar(10)  PRIMARY KEY,                 -- ISO 3166-2: JP-13, US-CA, CN-GD
    country_code        char(2)      NOT NULL REFERENCES master.country,
    name                varchar(150) NOT NULL,                    -- ISO name: 'Guangdong Sheng', 'Tokyo'
    short_name          varchar(150) NOT NULL,                    -- for display / matching: 'Guangdong'
    ascii_name          varchar(150) NOT NULL,                    -- without accents, for matching typed input
    type                varchar(60),                              -- State, Province, Prefecture, Municipality ...
    parent_code         varchar(10)  REFERENCES master.subdivision
);
CREATE INDEX IF NOT EXISTS subdivision_country_ix ON master.subdivision (country_code);

-- Other spellings of a subdivision ('Neimenggu' / 'Inner Mongolia' -> CN-NM, 'Tokyo-to' -> JP-13).
CREATE TABLE IF NOT EXISTS master.subdivision_alias (
    alias_norm          varchar(150) NOT NULL,                    -- upper(trim(alias)), single spaces
    alias               varchar(150) NOT NULL,
    subdivision_code    varchar(10)  NOT NULL REFERENCES master.subdivision,
    source              varchar(40)  NOT NULL,                    -- ISO, TARIFF_TABLE, MANUAL
    PRIMARY KEY (alias_norm, subdivision_code)                    -- one spelling can exist in several countries
);

CREATE TABLE IF NOT EXISTS master.city (
    city_id             serial       PRIMARY KEY,
    country_code        char(2)      NOT NULL REFERENCES master.country,
    subdivision_code    varchar(10)  REFERENCES master.subdivision,
    name                varchar(150) NOT NULL,                    -- English
    name_local          varchar(150),                             -- local script
    iata_code           char(3),                                  -- nearest airport, helps service-area lookup
    UNIQUE (country_code, subdivision_code, name)
);

-- Alternative spellings of a city ('Bombay' -> Mumbai, 'Peking' -> Beijing, local script).
CREATE TABLE IF NOT EXISTS master.city_alias (
    alias_norm          varchar(150) NOT NULL,
    city_id             int          NOT NULL REFERENCES master.city ON DELETE CASCADE,
    PRIMARY KEY (alias_norm, city_id)
);

-- Postcode ranges -> state and city. Source: national post data (USPS ZIP3, Japan Post KEN_ALL, ...).
-- Postcodes are compared as normalised text (upper case, no spaces) of equal length to the range bounds.
CREATE TABLE IF NOT EXISTS master.postcode_area (
    country_code        char(2)      NOT NULL REFERENCES master.country,
    postcode_from       varchar(12)  NOT NULL,
    postcode_to         varchar(12)  NOT NULL,
    subdivision_code    varchar(10)  REFERENCES master.subdivision,
    city_id             int          REFERENCES master.city,
    source              varchar(60)  NOT NULL,
    PRIMARY KEY (country_code, postcode_from, postcode_to)
);

-- -----------------------------------------------------------------------------
-- 3. Carrier geography
-- -----------------------------------------------------------------------------
-- Named sites a tariff starts or ends at (warehouses, hubs). The search offers these as places.
CREATE TABLE IF NOT EXISTS master.carrier_location (
    carrier_code        varchar(10)  NOT NULL,
    location_code       varchar(40)  NOT NULL,
    name                varchar(150) NOT NULL,
    kind                varchar(20)  NOT NULL DEFAULT 'WAREHOUSE', -- WAREHOUSE, HUB, GATEWAY, AIRPORT
    country_code        char(2)      NOT NULL REFERENCES master.country,
    subdivision_code    varchar(10)  REFERENCES master.subdivision,
    city                varchar(150),
    postcode            varchar(12),
    tariff_place_value  varchar(200),                             -- value stored in tariff.*.origin_city today
    note                text,
    PRIMARY KEY (carrier_code, location_code)
);

-- Carrier stations (service areas). Some carriers split a country by station: 'LHR', 'FRA'.
CREATE TABLE IF NOT EXISTS master.service_area (
    carrier_code        varchar(10)  NOT NULL,
    country_code        char(2)      NOT NULL REFERENCES master.country,
    station_code        varchar(5)   NOT NULL,
    name                varchar(150) NOT NULL,
    PRIMARY KEY (carrier_code, country_code, station_code)
);

-- Postcode -> station. NOT in any rate card: must come from the carrier (postcode / service-area list).
CREATE TABLE IF NOT EXISTS master.service_area_postcode (
    carrier_code        varchar(10)  NOT NULL,
    country_code        char(2)      NOT NULL,
    postcode_from       varchar(12)  NOT NULL,
    postcode_to         varchar(12)  NOT NULL,
    station_code        varchar(5)   NOT NULL,
    PRIMARY KEY (carrier_code, country_code, postcode_from, postcode_to),
    FOREIGN KEY (carrier_code, country_code, station_code) REFERENCES master.service_area
);

-- A zone scheme = one carrier's way of zoning one product from one rate card.
-- Example: B1C04 / BE export economy; B1C05 / US ground from origin ZIP 940; B1C06 / JP districts.
CREATE TABLE IF NOT EXISTS master.zone_scheme (
    scheme_id           serial       PRIMARY KEY,
    scheme_code         varchar(80)  NOT NULL UNIQUE,             -- carrier/country/service/direction
    carrier_code        varchar(10)  NOT NULL,
    mode                varchar(10)  NOT NULL,                    -- GROUND, AIR
    service_type        varchar(40),                              -- NULL = all services of the rate card
    direction           varchar(20)  NOT NULL,                    -- EXPORT, IMPORT, THIRD_COUNTRY, DOMESTIC
    home_country_code   char(2)      REFERENCES master.country,   -- the rate card's own country
    zone_basis          varchar(20)  NOT NULL,                    -- COUNTRY, SERVICE_AREA, SUBDIVISION, POSTCODE, POSTCODE_PAIR, CITY
    rate_card           varchar(80),                              -- e.g. EMEA_V01_BE (tariff_version / source_ref)
    source_sheet        varchar(100),
    valid_from          date,
    valid_to            date
);

CREATE TABLE IF NOT EXISTS master.zone (
    scheme_id           int          NOT NULL REFERENCES master.zone_scheme ON DELETE CASCADE,
    zone_code           varchar(40)  NOT NULL,                    -- as stored in tariff.*.dest_region / origin_region
    name                varchar(100),
    PRIMARY KEY (scheme_id, zone_code)
);

-- What a zone contains. Exactly one of the place columns is the key for a row, by zone_basis:
--   COUNTRY       country_code
--   SERVICE_AREA  country_code + service_group ('*1') -> master.service_group
--   SUBDIVISION   subdivision_code
--   POSTCODE      country_code + postcode_from/to
--   CITY          country_code + city_id
-- basis: FILE (stated on the rate card), CARRIER (from carrier, outside the rate card), ASSUMED (to confirm).
CREATE TABLE IF NOT EXISTS master.zone_member (
    member_id           serial       PRIMARY KEY,
    scheme_id           int          NOT NULL,
    zone_code           varchar(40)  NOT NULL,
    country_code        char(2)      REFERENCES master.country,
    service_group       varchar(5),
    subdivision_code    varchar(10)  REFERENCES master.subdivision,
    postcode_from       varchar(12),
    postcode_to         varchar(12),
    city_id             int          REFERENCES master.city,
    basis               varchar(10)  NOT NULL DEFAULT 'FILE',
    note                text,
    FOREIGN KEY (scheme_id, zone_code) REFERENCES master.zone ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS zone_member_lookup_ix ON master.zone_member (scheme_id, country_code, subdivision_code);

-- On a rate card, '*1', '*2' split a country into groups of stations (or 'rest of country').
-- The same label means different stations on different rate cards, so groups belong to a scheme.
CREATE TABLE IF NOT EXISTS master.service_group (
    scheme_id           int          NOT NULL REFERENCES master.zone_scheme ON DELETE CASCADE,
    country_code        char(2)      NOT NULL REFERENCES master.country,
    service_group       varchar(5)   NOT NULL,                    -- '*1'
    rest_of_country     boolean      NOT NULL DEFAULT false,      -- true: every station not listed in another group
    PRIMARY KEY (scheme_id, country_code, service_group)
);
CREATE TABLE IF NOT EXISTS master.service_group_station (
    scheme_id           int          NOT NULL,
    country_code        char(2)      NOT NULL,
    service_group       varchar(5)   NOT NULL,
    station_code        varchar(5)   NOT NULL,
    PRIMARY KEY (scheme_id, country_code, service_group, station_code),
    FOREIGN KEY (scheme_id, country_code, service_group) REFERENCES master.service_group ON DELETE CASCADE
);

-- Two-sided zoning: origin zone x destination zone -> the rate group (column letter) the price table uses.
CREATE TABLE IF NOT EXISTS master.zone_matrix (
    scheme_id           int          NOT NULL REFERENCES master.zone_scheme ON DELETE CASCADE,
    origin_zone         varchar(40)  NOT NULL,
    dest_zone           varchar(40)  NOT NULL,
    rate_group          varchar(40)  NOT NULL,
    PRIMARY KEY (scheme_id, origin_zone, dest_zone)
);

-- Postcode-pair zone charts (US parcel carriers: origin ZIP3 x destination ZIP3 -> zone).
CREATE TABLE IF NOT EXISTS master.postal_zone_chart (
    carrier_code        varchar(10)  NOT NULL,
    chart_code          varchar(40)  NOT NULL,                    -- one chart per origin ZIP3 range
    service_family      varchar(40)  NOT NULL,                    -- GROUND, AIR, INTERNATIONAL ...
    origin_from         varchar(12)  NOT NULL,
    origin_to           varchar(12)  NOT NULL,
    dest_from           varchar(12)  NOT NULL,
    dest_to             varchar(12)  NOT NULL,
    zone_code           varchar(10)  NOT NULL,                    -- '002' .. '008', '044' ...
    valid_from          date,
    PRIMARY KEY (carrier_code, chart_code, service_family, dest_from)
);

-- -----------------------------------------------------------------------------
-- 4. Pricing parameters a rate card states once (not per row)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS master.carrier_pricing_rule (
    carrier_code        varchar(10)  NOT NULL,
    mode                varchar(10)  NOT NULL,
    service_type        varchar(40)  NOT NULL DEFAULT '*',        -- '*' = every service of the carrier
    rule_code           varchar(40)  NOT NULL,                    -- VOLUMETRIC_DIVISOR, WEIGHT_ROUNDING_KG, MIN_BILLED_KG, WEIGHT_UNIT
    value_num           numeric,
    value_text          varchar(100),
    source              varchar(200),
    PRIMARY KEY (carrier_code, mode, service_type, rule_code)
);

-- -----------------------------------------------------------------------------
-- 5. Labels and units
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS master.code_list (
    list_name           varchar(40)  NOT NULL,                    -- service_type, piece_type, charge_basis ...
    code                varchar(60)  NOT NULL,                    -- value stored in tariff.*
    label               varchar(150) NOT NULL,                    -- what the filter shows
    description         text,
    sort_order          int          NOT NULL DEFAULT 0,
    PRIMARY KEY (list_name, code)
);

CREATE TABLE IF NOT EXISTS master.currency (
    currency_code       char(3)      PRIMARY KEY,
    name                varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS master.unit_conversion (
    from_unit           varchar(10)  NOT NULL,
    to_unit             varchar(10)  NOT NULL,
    factor              numeric      NOT NULL,                    -- value_in_to_unit = value_in_from_unit * factor
    PRIMARY KEY (from_unit, to_unit)
);

-- -----------------------------------------------------------------------------
-- 6. Lookups the search can call
-- -----------------------------------------------------------------------------
-- Normalise a printed country name to its code ('Czech Rep., The' -> 'CZ'). NULL when unknown.
CREATE OR REPLACE FUNCTION master.country_code_of(p_name text)
RETURNS char(2) LANGUAGE sql STABLE AS $$
    SELECT country_code FROM master.country_alias
    WHERE alias_norm = upper(regexp_replace(trim(p_name), '\s+', ' ', 'g'))
$$;

-- Normalise a typed or printed subdivision name within a country ('Guangdong Sheng', 'Neimenggu', 'Tokyo').
CREATE OR REPLACE FUNCTION master.subdivision_code_of(p_country char(2), p_name text)
RETURNS varchar(10) LANGUAGE sql STABLE AS $$
    SELECT a.subdivision_code FROM master.subdivision_alias a
    JOIN master.subdivision s ON s.subdivision_code = a.subdivision_code
    WHERE s.country_code = p_country
      AND a.alias_norm = upper(regexp_replace(trim(p_name), '\s+', ' ', 'g'))
    LIMIT 1
$$;

-- The subdivision a postcode belongs to (needs master.postcode_area to be loaded for that country).
CREATE OR REPLACE FUNCTION master.subdivision_of_postcode(p_country char(2), p_postcode text)
RETURNS varchar(10) LANGUAGE sql STABLE AS $$
    SELECT a.subdivision_code
    FROM master.postcode_area a
    WHERE a.country_code = p_country
      AND left(upper(replace(p_postcode, ' ', '')), length(a.postcode_from)) BETWEEN a.postcode_from AND a.postcode_to
    ORDER BY length(a.postcode_from) DESC
    LIMIT 1
$$;

-- The carrier station a postcode belongs to (needs master.service_area_postcode from the carrier).
CREATE OR REPLACE FUNCTION master.station_of_postcode(p_carrier text, p_country char(2), p_postcode text)
RETURNS varchar(5) LANGUAGE sql STABLE AS $$
    SELECT s.station_code
    FROM master.service_area_postcode s
    WHERE s.carrier_code = p_carrier AND s.country_code = p_country
      AND left(upper(replace(p_postcode, ' ', '')), length(s.postcode_from)) BETWEEN s.postcode_from AND s.postcode_to
    ORDER BY length(s.postcode_from) DESC
    LIMIT 1
$$;

-- The zone of an address in one scheme. Tries, in order: postcode range, city, subdivision,
-- service group (station listed, else the 'rest of country' group), whole country.
-- Returns NULL when the address cannot be placed: the search must then say so, not guess.
CREATE OR REPLACE FUNCTION master.zone_of(
    p_scheme_id int, p_country char(2), p_postcode text DEFAULT NULL,
    p_city_id int DEFAULT NULL, p_subdivision varchar(10) DEFAULT NULL)
RETURNS varchar(40) LANGUAGE plpgsql STABLE AS $$
DECLARE
    v_zone    varchar(40);
    v_pc      text := upper(replace(coalesce(p_postcode, ''), ' ', ''));
    v_sub     varchar(10) := coalesce(p_subdivision,
                                      CASE WHEN p_postcode IS NOT NULL THEN master.subdivision_of_postcode(p_country, p_postcode) END);
    v_carrier varchar(10);
    v_station varchar(5);
BEGIN
    IF v_pc <> '' THEN
        SELECT zone_code INTO v_zone FROM master.zone_member
        WHERE scheme_id = p_scheme_id AND country_code = p_country AND postcode_from IS NOT NULL
          AND left(v_pc, length(postcode_from)) BETWEEN postcode_from AND postcode_to
        ORDER BY length(postcode_from) DESC LIMIT 1;
        IF FOUND THEN RETURN v_zone; END IF;
    END IF;

    IF p_city_id IS NOT NULL THEN
        SELECT zone_code INTO v_zone FROM master.zone_member
        WHERE scheme_id = p_scheme_id AND city_id = p_city_id LIMIT 1;
        IF FOUND THEN RETURN v_zone; END IF;
    END IF;

    IF v_sub IS NOT NULL THEN
        SELECT zone_code INTO v_zone FROM master.zone_member
        WHERE scheme_id = p_scheme_id AND subdivision_code = v_sub LIMIT 1;
        IF FOUND THEN RETURN v_zone; END IF;
    END IF;

    IF EXISTS (SELECT 1 FROM master.service_group WHERE scheme_id = p_scheme_id AND country_code = p_country) THEN
        SELECT carrier_code INTO v_carrier FROM master.zone_scheme WHERE scheme_id = p_scheme_id;
        v_station := CASE WHEN v_pc <> '' THEN master.station_of_postcode(v_carrier, p_country, v_pc) END;
        IF v_station IS NULL THEN
            RETURN NULL;   -- the country is split by station and the station is unknown: do not guess
        END IF;
        SELECT m.zone_code INTO v_zone
        FROM master.zone_member m
        JOIN master.service_group g ON g.scheme_id = m.scheme_id AND g.country_code = m.country_code AND g.service_group = m.service_group
        WHERE m.scheme_id = p_scheme_id AND m.country_code = p_country
          AND (EXISTS (SELECT 1 FROM master.service_group_station s
                       WHERE s.scheme_id = g.scheme_id AND s.country_code = g.country_code
                         AND s.service_group = g.service_group AND s.station_code = v_station)
               OR (g.rest_of_country AND NOT EXISTS (
                       SELECT 1 FROM master.service_group_station s
                       WHERE s.scheme_id = g.scheme_id AND s.country_code = g.country_code AND s.station_code = v_station)))
        LIMIT 1;
        RETURN v_zone;
    END IF;

    SELECT zone_code INTO v_zone FROM master.zone_member
    WHERE scheme_id = p_scheme_id AND country_code = p_country
      AND service_group IS NULL AND subdivision_code IS NULL AND postcode_from IS NULL AND city_id IS NULL
    LIMIT 1;
    RETURN v_zone;
END $$;

-- Country list for the filter: full name, ISO code as value.
CREATE OR REPLACE VIEW master.v_country_option AS
SELECT country_code AS value, name || ' (' || country_code || ')' AS label, name
FROM master.country WHERE active
ORDER BY name;
